version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: your_db_username
      DATABASE_PASSWORD: your_db_password
      DATABASE_URL: jdbc:mysql://db:3306/happymarket
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: happymarket
      MYSQL_USER: your_db_username
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend/happymart
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  db_data:
